apiVersion: v1
kind: Secret
metadata:
  name: campusconnect-secrets
  namespace: campusconnect
type: Opaque
stringData:
  JWT_SECRET: "k8s_super_secret_jwt_key_campusconnect_prod_2026"
  JWT_REFRESH_SECRET: "k8s_super_secret_refresh_key_campusconnect_prod_2026"
  SENTRY_DSN: "https://examplePublicKey@o0.ingest.sentry.io/0"
  EMAIL_USER: "smtp-user@campusconnect.edu"
  EMAIL_PASS: "smtp-secure-password"
